name: CI

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system dependencies (libudev)
        run: sudo apt-get update && sudo apt-get install -y libudev-dev

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Cargo Format (fail on bad formatting)
        run: cargo fmt --all --check

      - name: Cargo Build (fails on errors, but not on warnings)
        run: cargo build --all-targets

      - name: Show Warnings in PR (does not stop PR merge)
        run: |
          echo "Compiler warnings:"
          cargo check --all-targets --message-format short
        continue-on-error: true
